
//import com.sun.jdi.connect.spi.Connection;
//import java.sql.*;

import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;





/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author venga
 */
public class NewMember extends javax.swing.JFrame {

    /**
     * Creates new form NewMember
     */
    public NewMember() {
        initComponents();
        try
          {
              int id = 1;
              String str1 = String.valueOf(id);
              txt_id.setText(str1);
              //String query = "select max(id) from tbl_gms";
              
              Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver"); 
            System.out.println("connection done");
            Connection conn=DriverManager.getConnection("jdbc:sqlserver://VENGAT;encrypt=true;TrustServerCertificate=true;databaseName=gms","gms","admin");
            
             
                PreparedStatement pst;
            String sql ="select max(id) from tbl_gms";
               
                pst =  conn.prepareStatement(sql);                    
                      ResultSet rs=  pst.executeQuery();      
                       

             
              while(rs.next())
              {
                id = rs.getInt(1);
                id = id+1;
                String str = String.valueOf(id);
                txt_id.setText(str);
              }
           }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,e );
                }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_close = new javax.swing.JButton();
        newmember = new javax.swing.JLabel();
        memberid = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        mobilenumber = new javax.swing.JLabel();
        txt_mobilenumber = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        genderbox = new javax.swing.JComboBox<>();
        age = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        aadharnumber = new javax.swing.JLabel();
        txt_aadhar = new javax.swing.JTextField();
        gymtime = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        txt_amount = new javax.swing.JTextField();
        gymtimebox = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 100));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_close.setBackground(new java.awt.Color(0, 118, 221));
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        newmember.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        newmember.setForeground(new java.awt.Color(0, 118, 221));
        newmember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new member.png"))); // NOI18N
        newmember.setText("New Member");

        memberid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        memberid.setForeground(new java.awt.Color(0, 118, 221));
        memberid.setText("Member ID :");

        name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(0, 118, 221));
        name.setText("Name");

        txt_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_name.setForeground(new java.awt.Color(0, 118, 221));
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        mobilenumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mobilenumber.setForeground(new java.awt.Color(0, 118, 221));
        mobilenumber.setText("Mobile Number");

        txt_mobilenumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_mobilenumber.setForeground(new java.awt.Color(0, 118, 221));

        email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(0, 118, 221));
        email.setText("Email");

        txt_email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(0, 118, 221));

        gender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gender.setForeground(new java.awt.Color(0, 118, 221));
        gender.setText("Gender");

        genderbox.setBackground(new java.awt.Color(0, 118, 221));
        genderbox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genderbox.setForeground(new java.awt.Color(0, 118, 221));
        genderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        genderbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderboxActionPerformed(evt);
            }
        });

        age.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        age.setForeground(new java.awt.Color(0, 118, 221));
        age.setText("Age");

        txt_age.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_age.setForeground(new java.awt.Color(0, 118, 221));

        aadharnumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aadharnumber.setForeground(new java.awt.Color(0, 118, 221));
        aadharnumber.setText("Aadhar no :");

        txt_aadhar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_aadhar.setForeground(new java.awt.Color(0, 118, 221));

        gymtime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gymtime.setForeground(new java.awt.Color(0, 118, 221));
        gymtime.setText("Gym time");

        amount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        amount.setForeground(new java.awt.Color(0, 118, 221));
        amount.setText("Amount to pay/month");

        txt_amount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_amount.setForeground(new java.awt.Color(0, 118, 221));

        gymtimebox.setBackground(new java.awt.Color(0, 118, 221));
        gymtimebox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gymtimebox.setForeground(new java.awt.Color(0, 118, 221));
        gymtimebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "05:00AM - 10:00AM", "04:00PM - 09:00PM" }));

        save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(0, 118, 221));
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 118, 221));
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        txt_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_id.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_close)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newmember)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 69, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(memberid)
                                .addGap(18, 18, 18)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(gender)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_name)
                                .addComponent(mobilenumber)
                                .addComponent(txt_mobilenumber)
                                .addComponent(email)
                                .addComponent(txt_email)
                                .addComponent(genderbox, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(save)
                                .addGap(154, 154, 154)
                                .addComponent(reset)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_age)
                            .addComponent(aadharnumber)
                            .addComponent(gymtime)
                            .addComponent(amount)
                            .addComponent(txt_aadhar)
                            .addComponent(gymtimebox, 0, 400, Short.MAX_VALUE)
                            .addComponent(txt_amount))
                        .addGap(60, 60, 60))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newmember)
                    .addComponent(btn_close))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberid)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(name)
                    .addComponent(age))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobilenumber)
                    .addComponent(aadharnumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_mobilenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_aadhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(gymtime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gender)
                            .addComponent(amount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(gymtimebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(reset))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void genderboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderboxActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new NewMember().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed
      
             PreparedStatement pst=null;
             
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
       
        
        try
        {
          
              String id = txt_id.getText();
              String name = txt_name.getText();
              String mobilenumber = txt_mobilenumber.getText();
              String email = txt_email.getText();
              String gender = (String)genderbox.getSelectedItem();
              String age = txt_age.getText();
              String aadharnumber = txt_aadhar.getText();
              String gymtime = (String)gymtimebox.getSelectedItem();
              String amount = txt_amount.getText();
              
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver"); 
            System.out.println("connection done");
            Connection conn=DriverManager.getConnection("jdbc:sqlserver://VENGAT;encrypt=true;TrustServerCertificate=true;databaseName=gms","gms","admin");
            
           
              String sql = "exec sp_newmember ?,?,?,?,?,?,?,?,?";
            System.out.println(sql);
            pst=conn.prepareStatement(sql);
            
            pst.setString(1, id);
            pst.setString(2, name);
            pst.setString(3 ,mobilenumber);
            pst.setString(4, email);
            pst.setString(5, gender);
            pst.setString(6, age);
            pst.setString(7, aadharnumber);
            pst.setString(8, gymtime);
            pst.setString(9, amount);

           
            
         
                   
                   int i=  pst.executeUpdate();
            if (i==0)
            {
                JOptionPane.showMessageDialog(null, "Data not inserted");
            }
                else
                {
                    JOptionPane.showMessageDialog(null, "Data inserted ");
                    setVisible(false);
                    new NewMember().setVisible(true);
                   
                } 
        }
        catch(Exception e)
        {
               JOptionPane.showMessageDialog(null, e);
        }
                    
               
        
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewMember().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aadharnumber;
    private javax.swing.JLabel age;
    private javax.swing.JLabel amount;
    private javax.swing.JButton btn_close;
    private javax.swing.JLabel email;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox<String> genderbox;
    private javax.swing.JLabel gymtime;
    private javax.swing.JComboBox<String> gymtimebox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel memberid;
    private javax.swing.JLabel mobilenumber;
    private javax.swing.JLabel name;
    private javax.swing.JLabel newmember;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JTextField txt_aadhar;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_mobilenumber;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables

   

   



   

       
     

   
}
